name: Maven Build

# Trigger the workflow on push to the master branch (adjust if your branch is different)
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner (matches Jenkins' typical environment)

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK (match your project's Java version)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Adjust to match your project's Java version (e.g., 11 if different)
          distribution: 'temurin'  # Eclipse Temurin is a reliable OpenJDK distribution
          cache: 'maven'  # Cache Maven dependencies to speed up builds

      # Step 3: Build with Maven
      - name: Build with Maven
        env:
          VALID_USERNAME: ${{ secrets.VALID_USERNAME }}  # Inject username from secrets
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}  # Inject password from secrets
        run: mvn clean install